export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  LOAN_OFFICER = 'LOAN_OFFICER',
  CUSTOMER = 'CUSTOMER',
  READ_ONLY = 'READ_ONLY',
}

export enum Permission {
  CREATE_CUSTOMER = 'CREATE_CUSTOMER',
  VIEW_CUSTOMER = 'VIEW_CUSTOMER',
  EDIT_CUSTOMER = 'EDIT_CUSTOMER',
  DELETE_CUSTOMER = 'DELETE_CUSTOMER',
  CREATE_LOAN = 'CREATE_LOAN',
  VIEW_LOAN = 'VIEW_LOAN',
  EDIT_LOAN = 'EDIT_LOAN',
  DELETE_LOAN = 'DELETE_LOAN',
  APPROVE_LOAN = 'APPROVE_LOAN',
  DISBURSE_LOAN = 'DISBURSE_LOAN',
  CREATE_USER = 'CREATE_USER',
  VIEW_USER = 'VIEW_USER',
  EDIT_USER = 'EDIT_USER',
  DELETE_USER = 'DELETE_USER',
  MANAGE_ROLES = 'MANAGE_ROLES',
  MANAGE_PERMISSIONS = 'MANAGE_PERMISSIONS',
  VIEW_REPORTS = 'VIEW_REPORTS',
  EXPORT_DATA = 'EXPORT_DATA',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum MaritalStatus {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
}

export enum LoanStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  DISBURSED = 'DISBURSED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  DEFAULTED = 'DEFAULTED',
}

export enum TenureUnit {
  DAYS = 'DAYS',
  WEEKS = 'WEEKS',
  MONTHS = 'MONTHS',
}

export enum DisbursementMethod {
  MPESA = 'MPESA',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CASH = 'CASH',
}
